SOURCE: MR
TARGET: CT
NUM_WORKERS: 4
FULLY_SUPERVISED: False
TRAIN:
  warmup_epoch: 100
  DA_METHOD: Ours
  MODEL: DeepLabv2
  RESTORE_FROM:   USD/experiments/snapshots/MR2CT/Adaoutput_MR2CT/model_best.pth
  D_AUX_RESTORE:  USD/experiments/snapshots/MR2CT/Adaoutput_MR2CT/model_best_D_aux.pth
  D_MAIN_RESTORE: USD/experiments/snapshots/MR2CT/Adaoutput_MR2CT/ct2mr_model_pretrained_D_main.pth
  CLASS_CENTER_FEA_INIT_TRG: /pretrained_model/testing/CT2MR_best_class_center_feas.npy 
  CLASS_CENTER_FEA_INIT_SRC: /pretrained_model/testing/MR2CT_best_class_center_feas.npy 
  D_TYPE:         PatchGAN
  D_NORM:          Batch_Norm
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN:      0.003
  LAMBDA_ADV_AUX:       0.00002
  LAMBDA_MPCL_SRC:       1.0
  LAMBDA_MPCL_TRG:       0.1
  CLASS_CENTER_M:       0.01
  PIXEL_SEL_TH:  0.25

  SRC_TEMP:      1.0
  SRC_BASE_TEMP: 1.0
  TRG_TEMP:      1.0
  TRG_BASE_TEMP: 1.0
  SRC_MARGIN:    0.4
  TRG_MARGIN:    0.2

  LAMBDA_DICE_SRC_MAIN:   1.0
  LAMBDA_DICE_SRC_AUX:    0.1

TEST:
  MODE: best

